FROM hub.contains.com/micro-service/openjdk:8-jre
MAINTAINER xxx xxx@contains.com

COPY target/user-edge-service-1.0-SNAPSHOT.jar /user-edge-service.jar

ENTRYPOINT ["java","-jar","/user-edge-service.jar"]
